POST http://localhost:8082/login
Content-Type: application/json

{
  "login": "admin1",
  "password": "admin"
}

###

GET http://localhost:8082/secret
auth-token: f47908af-ab02-4c13-bd8b-30d3f9cf984e

###

POST http://localhost:8082/logout
auth-token: 01460210-c6e0-4f28-86cc-c54a47f920b7