server:
  port: ${APPLICATION_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  token:
    time-to-live: 3600
